- name: Community General Role
   src: https://github.com/ansible-collections/community.general
   version: 1.3.7

- name: Community Crypto Role
  src: https://github.com/ansible-collections/community.crypto
  version: 1.4.0
