- name: Nomad configuration directory
  ansible.builtin.file:
    path: '{{ nomad_config_dir }}'
    owner: root
    group: root
    mode: '0644'
    state: directory

- name: Nomad data directory
  ansible.builtin.file:
    path: '{{ nomad_data_dir }}'
    mode: '0755'
    owner: 'root'
    group: 'root'
    state: directory

- name: Nomad common configuration
  template:
    src: files/nomad/micro-cloud-common.hcl
    dest: "{{ nomad_config_dir }}/micro-cloud-common.hcl"

- name: Nomad Server configuration
  template:
    src: files/nomad/micro-cloud-server.hcl
    dest: "{{ nomad_config_dir }}/micro-cloud-server.hcl"

- name: Nomad Client configuration
  template:
    src: files/nomad/micro-cloud-client.hcl
    dest: "{{ nomad_config_dir }}/micro-cloud-client.hcl"

- name: Nomad systemd service
  template:
    src: files/nomad/nomad.service
    dest: "{{ systemd_service_dir }}/nomad.service"
    owner: root
    group: root
    mode: '0644'
  notify: restart nomad

- name: Start Nomad service
  systemd:
    name: nomad
    state: started
    enabled: yes
    daemon_reload: yes
