- name: Enable SSH
  ansible.builtin.systemd:
    name: ssh
    state: started
    enabled: yes

- name: SSH Authorized Keys
  ansible.builtin.lineinfile:
    path: /home/{{ admin_user }}/.ssh/authorized_keys
    mode: '0644'
    line: '{{ item }}'
    create: yes
  loop: '{{ authorized_keys }}'
